"""
App launcher, closer, and close-all.
open_app uses app_paths.py (generated by scan_apps.py) for lookup,
with fuzzy matching so "chrome" finds "google chrome", etc.
"""
import os
import subprocess
import difflib

from .app_paths import APPS

# Common spoken names that don't match the Start Menu key
_ALIASES: dict[str, str] = {
    "vs code":        "visual studio code",
    "vscode":         "visual studio code",
    "visual studio code": "visual studio code",
    "code":           "visual studio code",
    "word":           "winword",
    "excel":          "excel",
    "powerpoint":     "powerpnt",
    "notepad++":      "notepad++",
    "7zip":           "7-zip file manager",
    "7 zip":          "7-zip file manager",
    "chrome":         "google chrome",
    "google chrome":  "google chrome",
    "edge":           "microsoft edge",
    "studio":         "android studio",
}


def _find_app(name: str) -> tuple[str, str] | None:
    """
    Return (matched_key, exe_path) for the best match to `name`, or None.
    Strategy:
      1. Exact key match
      2. Key starts with the query
      3. Query is a substring of a key
      4. difflib close-match (cutoff 0.6)
    """
    query = name.lower().strip()

    # 0. Alias remap
    if query in _ALIASES:
        query = _ALIASES[query]

    # 1. Exact
    if query in APPS:
        return query, APPS[query]

    # 2. Key starts with query
    for key, path in APPS.items():
        if key.startswith(query):
            return key, path

    # 3. Substring
    for key, path in APPS.items():
        if query in key:
            return key, path

    # 4. Fuzzy
    matches = difflib.get_close_matches(query, APPS.keys(), n=1, cutoff=0.6)
    if matches:
        key = matches[0]
        return key, APPS[key]

    # 5. PATH fallback — try it as a plain executable name
    import shutil
    found = shutil.which(query) or shutil.which(query + ".exe")
    if found:
        return query, found

    return None


def open_app(args: dict) -> str:
    name = args.get("name", "").strip()
    if not name:
        return "no app name provided"

    match = _find_app(name)
    if match is None:
        return f"app '{name}' not found — run scan_apps.py to refresh the list"

    matched_key, exe_path = match
    if os.path.exists(exe_path):
        os.startfile(exe_path)
    else:
        subprocess.Popen(exe_path, shell=True)
    return f"opened '{matched_key}' ({exe_path})"


