"""
Run this script once (or whenever you install new apps) to rebuild app_paths.py.

    python scan_apps.py

It scans:
  - Windows Registry  HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths
  - Start Menu shortcuts  (system-wide + per-user)
and writes every resolved .exe path into app_paths.py as a plain dict.
"""
import os
import glob
import winreg
from pathlib import Path

import pythoncom          # noqa: F401  (needed for COM init)
import win32com.client


def _collect() -> dict[str, str]:
    apps: dict[str, str] = {}

    # ── 1. Registry App Paths ──────────────────────────────────────────────
    try:
        key = winreg.OpenKey(
            winreg.HKEY_LOCAL_MACHINE,
            r"SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths",
        )
        for i in range(winreg.QueryInfoKey(key)[0]):
            exe_name = winreg.EnumKey(key, i)
            try:
                sub = winreg.OpenKey(key, exe_name)
                val, _ = winreg.QueryValueEx(sub, "")
                val = val.strip('"').strip()
                if val and os.path.exists(val):
                    friendly = exe_name.lower().replace(".exe", "").strip()
                    apps[friendly] = val
            except OSError:
                pass
    except OSError:
        pass

    # ── 2. Start Menu .lnk shortcuts ──────────────────────────────────────
    shell = win32com.client.Dispatch("WScript.Shell")
    search_roots = [
        r"C:\ProgramData\Microsoft\Windows\Start Menu\Programs",
        os.path.expanduser(r"~\AppData\Roaming\Microsoft\Windows\Start Menu\Programs"),
    ]
    for base in search_roots:
        for lnk in glob.glob(base + "/**/*.lnk", recursive=True):
            try:
                sc = shell.CreateShortcut(lnk)
                target = sc.TargetPath.strip()
                if target and target.lower().endswith(".exe") and os.path.exists(target):
                    friendly = Path(lnk).stem.lower().strip()
                    apps[friendly] = target
            except Exception:
                pass

    return dict(sorted(apps.items()))


def _write(apps: dict[str, str], out_path: str | None = None):
    if out_path is None:
        out_path = str(Path(__file__).parent / "app_paths.py")
    lines = [
        '"""Auto-generated by scan_apps.py — do not edit by hand. Run scan_apps.py to refresh."""',
        "",
        "APPS: dict[str, str] = {",
    ]
    for name, path in apps.items():
        lines.append(f'    {name!r}: {path!r},')
    lines += ["}", ""]
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Wrote {len(apps)} apps to {out_path}")


def main():
    found = _collect()
    _write(found)


if __name__ == "__main__":
    main()
